### PR TITLE
Change github_deploy_key.enc to new value from 'doctr configure'.

### PR DESCRIPTION
**Pull request by efiring**
The script did not complete, however; it ended with 
```
================== You should now do the following ==================

1. Commit the file github_deploy_key.enc.

Traceback (most recent call last):
  File "/Users/efiring/anaconda/envs/test/bin/doctr", line 11, in <module>
    sys.exit(main())
  File "/Users/efiring/anaconda/envs/test/lib/python3.5/site-packages/doctr/__main__.py", line 393, in main
    return process_args(get_parser(config=config))
  File "/Users/efiring/anaconda/envs/test/lib/python3.5/site-packages/doctr/__main__.py", line 211, in process_args
    return args.func(args, parser)
  File "/Users/efiring/anaconda/envs/test/lib/python3.5/site-packages/doctr/__main__.py", line 379, in configure
    """.format(options=options, N=N)))
KeyError: 'deploy_directory'
```

### CODE REVIEW

**Comment by ocefpaf** [comment]
We need to check of `doctr` successfully added the key and we need to commit `github_deploy_key.enc` too.

**Comment by efiring** [comment]
The key was added:
```
The following SSH key was added to the TEOS-10/python-gsw repository by efiring:

Doctr deploy key for pushing to gh-pages from Travis
5e:22:66:d1:2c:60:b3:a9:58:4d:17:c6:e9:62:13:b2

If you believe this key was added in error, you can remove the key and disable
access at the following location:

https://github.com/TEOS-10/python-gsw/settings/keys
```

**Comment by ocefpaf** [comment]
> we need to commit github_deploy_key.enc too.

Sorry I meant update the secret in `.travis.yml`. See https://github.com/TEOS-10/python-gsw/blob/master/.travis.yml#L7

**Comment by efiring** [comment]
But where does that come from?

**Comment by ocefpaf** [comment]
I guess that b/c the command fail you mat not have seen it.

**Comment by ocefpaf** [comment]
> But where does that come from?

@efiring the `doctr` failure is fixed and we can retry this as when the new release is up.
See https://github.com/drdoctr/doctr/issues/179

**Pull request merged**
